### PR TITLE
Add login_emailusername

### PR DESCRIPTION
**Pull request by phenaproxima**
Logging in by username only is outmoded and inconvenient. Let's make it possible to login with your email address. I haven't personally used this module before but it has a solid install base and claims to be zero configuration.

I'll leave the final decision to commit to @pameeela or someone else who actually builds sites, but from a value perspective, in my personal opinion, this feels like the no-braineriest of no-brainers.

### CODE REVIEW

**Comment by phenaproxima** [comment]
The other module that might make sense for this is https://www.drupal.org/project/mail_login. Not sure which one is better, though. Mail Login has more installs, and seems more configurable, but I don't know how desirability more configuration options are in this case. I'd love to hear some input.

**Comment by phenaproxima** [comment]
https://www.drupal.org/project/email_registration is another one, with even _more_ installs.

**Comment by pameeela** [comment]
I totally agree that logging in with your email address is a no-brainer. Personally, I always just use the email address as the username when creating accounts, so people don't have to remember yet another thing. 

But how to resolve this is not that simple IMO. The simplest (from the perspective of what we already have) is to keep the username as a thing but also allow users to login using their email address, which login_emailusername and mail_login do. The other approach, and what email_registration does, is basically remove the username from the process altogether. For me that is a harder sell because it's kind of at odds with core?

Overall I am a huge +1 on this idea but not sure of the best approach. If we go with the first option, I would be in favour of no config required, just keep it simple. 

Curious what others think!

**Comment by phenaproxima** [comment]
I definitely prefer something that's not "fightning" core. I don't think we need to remove usernames from the equation, at least not for now. But allowing login by email feels borderline essential.

**Comment by phenaproxima** [comment]
It's worth discussing which solution to use for the long term, but the beauty of recipes is that we can always change it later. In the meantime, though, this feature is so obviously useful that I think it makes more sense to ask for forgiveness than permission. I'll merge it.

**Pull request merged**
