### PR TITLE
Install Project Browser with recipe support

### PR DESCRIPTION
**Pull request by phenaproxima**
This PR installs Project Browser by default in Starshot, patching it with https://www.drupal.org/project/project_browser/issues/3446257 so that it displays recipes, plus the commands to install them.

Right now, it only shows `starshot_multilingual` -- which is no longer installed with Starshot by default. We can show all the recipes in Starshot once we have a reliable way to display whether they've been previously applied or not.

### CODE REVIEW

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-fgsly536vb2k2m1utzocepdfkmz1bpng.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6643b20b9c8701badf362058

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-fgsly536vb2k2m1utzocepdfkmz1bpng.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6643b20b9c8701badf362058

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-fgsly536vb2k2m1utzocepdfkmz1bpng.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6643b20b9c8701badf362058

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-fgsly536vb2k2m1utzocepdfkmz1bpng.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6643b20b9c8701badf362058

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-fgsly536vb2k2m1utzocepdfkmz1bpng.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6643b20b9c8701badf362058

**Comment by pameeela** [comment]
Tested this manually, and it works, but.... 1) I wasn't expecting it to hijack PB and *only* show this one recipe, so it kind of ruins PB for Starshot and 2) the suggested command was not valid using the suggested `ddev install` command for setup.

The suggested command was `/usr/bin/php /var/www/html/web/core/scripts/drupal recipe /var/www/html/recipes/starshot_multilingual`

I'm not really sure what to suggest though, there probably isn't a way to get it exactly right for everyone? Do we want to worry about this?

The disabling of PB is probably more of a concern.

**Comment by phenaproxima** [comment]
> the suggested command was not valid using the suggested ddev install command for setup.

Yeah, your assessment is correct. You would need to run that command from inside the DDEV container. However, that's a preexisting problem; Project Browser has no way to detect reliably if we're running within DDEV, and even if it did, it can't reliably generate the correct commands. You'd have the same problem if you were browsing regular modules. This problem will be fixed once Project Browser can actually apply recipes in the UI - which is a goal, but it's a bit of a ways off because there is a sizable chunk of work needed in Project Browser to make that work. Any suggestions?

I'm a bit confused when you say PB is "disabled"; this doesn't (shouldn't?) disable anything, it just adds recipes as a type of project to be browsed. I'll see what I can do about that.

**Comment by phenaproxima** [comment]
> I wasn't expecting it to hijack PB and only show this one recipe

Fixed this in fed0192e16fc87a9293f87e2a0ee4998354e0e21.

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-velmhpngriay5nlknnafzqwpnye334yb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66465b12aea98b08f1883e2f

**Comment by phenaproxima** [comment]
I've also added something to the README explaining how to run Project Browser commands in DDEV. It's actually pretty straightforward; just run `ddev ssh` first. Fixed in 91aefeadb6cdf10490201a6dd66ce986ee777034.

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-velmhpngriay5nlknnafzqwpnye334yb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66465b12aea98b08f1883e2f

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-velmhpngriay5nlknnafzqwpnye334yb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66465b12aea98b08f1883e2f

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr74-velmhpngriay5nlknnafzqwpnye334yb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66465b12aea98b08f1883e2f

**Pull request merged**
