### PR TITLE
Add a few DDEV bash aliases

### PR DESCRIPTION
**Pull request by TravisCarden**
What would you think of a few convenience aliases, @phenaproxima?

### CODE REVIEW

**Comment by gitressa** [comment]
That's a great idea, I added these to the Drupal documentation a while ago:

```
# DDEV, Drush, and Composer aliases
alias dstart='ddev start'
alias dstop='ddev stop'
alias drush='ddev drush'
alias din='ddev drush install'
alias dun='ddev drush pm:uninstall'
alias duli='ddev drush uli'
alias creq='ddev composer require'
alias crem='ddev composer remove'
```

From [Working efficiently with the command line  > DDEV, Drush, and Composer aliases](https://www.drupal.org/docs/develop/development-tools/working-efficiently-with-the-command-line#s-ddev-drush-and-composer-aliases).

**Comment by alexb7217** [comment]
Man I waste a lot of keystrokes on those commands.

What are you all working on, with Starshot and some kind of Ubuntu container?

**Comment by TravisCarden** [comment]
Merging. @alexb7217, these are for [DDEV](https://github.com/ddev/ddev). We don't have any documentation on it. If you want to provide or propose some, feel free to open an issue. 🙂

**Comment by alexb7217** [comment]
@TravisCarden are you saying the documentation in the README needs expansion?  https://github.com/phenaproxima/starshot-prototype?tab=readme-ov-file#using-project-browser-with-ddev 

I am happy to attempt to provide DDEV related documentation for this project if it would be useful.

**Comment by TravisCarden** [comment]
Yes, @alexb7217. Most of the effort on this project so far has gone into solving the major technological challenges, so _any_ help with documentation is very welcome. As of this week, I'm focusing on project setup, including DDEV, so your feedback would be timely. I've created https://github.com/phenaproxima/starshot-prototype/issues/126 as a place to share it. Thanks!

**Comment by alexb7217** [comment]
This is merged, making a note I think I get the intent of the aliases.

The `.homeadditions/.bash_aliases` add some convenience methods inside the container. 

So, `ddev ssh` and then `dr foo-command` to run commands in shell, for example. 

Will look again at the list offered here: https://github.com/phenaproxima/starshot-prototype/pull/120#issuecomment-2188261367

And looking for ways to use and describe aliases for documentation as well.

**Comment by isalmanhaider** [comment]
Why not consider switching to Fish shell? It enhances the command-line experience by providing autocompletion for your most-used and recent commands. Additionally, Fish offers real-time feedback by highlighting command syntax to indicate whether commands are correct or recognized. This can significantly streamline workflows - while you can further amplify the experience with short aliases on top of Fish.

Fish shell is also particularly effective for Git operations. It can automatically suggest Git branches and commands as you type, which simplifies navigating through your repositories and enhances your version control workflow.

While `ddev ssh` is efficient, it typically requires typing out full commands repeatedly or cycling through command history with the arrow keys. By adopting Fish shell, you can reduce repetitive typing and increase productivity, making it a superior choice for managing commands within the shell.

Or else configuring Fish inside of DDEV globally or for a specific project.

**Pull request merged**
