### PR TITLE
To respect user privacy, use Geocoder & Leaflet on the event content type

### LINKED ISSUE #81: Use Geofield and Leaflet modules for maps, to respect user privacy
To respect user privacy, usage of external resources should be kept at a minimum, or avoided entirely.

The Geolocation module contacts the external web site unpkg.com for the https://unpkg.com/leaflet@1.8.0/dist/leaflet.js file, when it shows the map on _/event/2024/nasas-boeing-crew-flight-test-launch_. The maintainer stated in [Allow to choose between local or external libraries](https://www.drupal.org/project/geolocation/issues/3023494) that:

> I think it's pretty likely that some people want to host the libraries locally, but they can do so using hook_js_alter() as they deem fit. Providing all the plumbing to handle this in a form and keeping this up to date in the future seems to much effort for an each case that can be solved fairly easily anyway.

So we could instead use [Geofield](https://www.drupal.org/project/geofield) module with the [Leaflet](https://www.drupal.org/project/leaflet/) module.

~~Leaflet module _does_ currently contact fastly.net, but as soon as [Support serving local scripts first, use CDN as fallback](https://www.drupal.org/project/leaflet/issues/3447832) is fixed, Geofield with Leaflet ought to only contact the relevant map resource, which is openstreetmap.org~~. I was mistaken, [OpenStreetMap uses fastly.net to serve its tiles](https://www.fastly.com/blog/how-openstreetmap-uses-our-modern-cdn-to-push-near-instant-updates-worldwide/), so fastly.net is necessary, and all is well with the Leaflet module.

## Remaining tasks

Switch from Geolocation to Geofield and Leaflet.

### PR DESCRIPTION
**Pull request by phenaproxima**
Fixes #81.

The sticking point for me on this one is that you have to set the user agent and referer on the geocoder provider. For the purposes of this PR, I'm having the install profile take care of that, but it breaks the self-contained nature of the starshot_event_content_type recipe. It requires the site builder to do some configuration, and there's no direction or documentation about that. It's obscure.

The install profile is not a long-term solution for this. I can think of two ways:

* Add a config action (to where? the install profile?) that sets up the user agent and referrer
* The Nominatim plugin should provide default values for the user agent and referer. This shouldn't be too tricky, and is my preferred solution. I'd be happy to patch Geocoder for this.

### CODE REVIEW

**Comment by gitressa** [comment]
This is great, and works well, thanks @phenaproxima. To get all the way, I think we should use openstreetmap.de instead of openstreetmap.org, via [Leaflet More Maps](https://www.drupal.org/project/leaflet_more_maps). This will also add support for a lot of other free and open source map providers to the user.

OpenStreetMap.org and the sites it contacts are located in countries outside EU, which conflicts with GDPR compliance:
- openstreetmap.org: Canada/United States
- fastly.net: Canada/United States

It's the final step in the process, which I outlined here:

> Two tips: I just  went through the process, and enabled the modules with Drush:
> 
> ```
> drush in address geocoder geofield leaflet leaflet_more_maps geocoder_address geocoder_geofield geocoder_field
> ```
> 
> Also, when setting the display to use "Leaflet Map" (Step 7) under settings, set "Leaflet Map Tiles Layer" to "OpenStreetMap.de".

From https://github.com/phenaproxima/starshot-prototype/issues/81#issuecomment-2184051684.

**Comment by thegbomb** [comment]
I pulled the branch and am still getting warnings:
`$ ddev quick-start
Starting starshot-prototype... 
Building project images... 
.Project images built in 1s. 
 Network ddev-starshot-prototype_default  Created 
 Container ddev-starshot-prototype-db  Created 
 Container ddev-starshot-prototype-web  Created 
 Container ddev-starshot-prototype-web  Started 
 Container ddev-starshot-prototype-db  Started 
Waiting for containers to become ready: [web db] 
Starting ddev-router if necessary... 
 Container ddev-router  Created 
 Container ddev-router  Started 
Waiting for additional project containers to become ready... 
All project containers are now ready. 
No settings.php file exists, creating one 
Successfully started starshot-prototype 
Project can be reached at https://starshot-prototype.ddev.site https://127.0.0.1:32776 
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 16 installs, 0 updates, 0 removals
  - Syncing drupal-eca-recipe/notify_new_comments (dev-main 1df55c1) into cache
  - Installing drupal/starshot_content_type_base (dev-main): Mirroring from recipes/starshot_content_type_base
  - Installing drupal/starshot_page_content_type (dev-main): Mirroring from recipes/starshot_page_content_type
  - Installing drupal/starshot_multilingual (dev-main): Mirroring from recipes/starshot_multilingual
  - Installing drupal/starshot_local_video_media_type (dev-main): Mirroring from recipes/starshot_local_video_media_type
  - Installing drupal/starshot_image_media_type (dev-main): Mirroring from recipes/starshot_image_media_type
  - Installing drupal/starshot_full_html_editor (dev-main): Mirroring from recipes/starshot_full_html_editor
  - Installing drupal/starshot_anti_spam (dev-main): Mirroring from recipes/starshot_anti_spam
  - Installing drupal/starshot_forms (dev-main): Mirroring from recipes/starshot_forms
  - Installing drupal/starshot_event_content_type (dev-main): Mirroring from recipes/starshot_event_content_type
  - Installing drupal/starshot_document_media_type (dev-main): Mirroring from recipes/starshot_document_media_type
  - Installing drupal-eca-recipe/notify_new_comments (dev-main 1df55c1): Cloning 1df55c1e01 from cache
  - Installing drupal/starshot_blog (dev-main): Mirroring from recipes/starshot_blog
  - Installing drupal/starshot_basic_html_editor (dev-main): Mirroring from recipes/starshot_basic_html_editor
  - Installing drupal/starshot_audio_media_type (dev-main): Mirroring from recipes/starshot_audio_media_type
  - Installing drupal/starshot_admin_theme (dev-main): Mirroring from recipes/starshot_admin_theme
  - Installing drupal/starshot (dev-main): Mirroring from recipes/starshot
Generating optimized autoload files
97 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
  * Homepage: https://www.drupal.org/project/drupal
  * Support:
    * docs: https://drupal.org/docs/user_guide/en/index.html
    * chat: https://drupal.org/node/314178
> Composer\Config::disableProcessTimeout
> \Drupal\starshot_installer\ScriptHandler::configureDrush
> drush site:install --yes --account-pass admin --config drush-install.yml && rm -f drush-install.yml
 You are about to:
 * DROP all tables in your 'db' database.

 // Do you want to continue?: yes.                                                                                      

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [notice] Performed install task: install_profile_modules
 [notice] Performed install task: install_profile_themes
 [notice] Performed install task: install_install_profile
 [notice] Performed install task: install_configure_form
 [warning] The "help_block" was not found
 [warning] The "field_block:node:event:field_image" was not found
 [warning] The "extra_field_block:node:event:links" was not found
 [warning] The "field_block:node:event:body" was not found
 [warning] The "extra_field_block:node:event:content_moderation_control" was not found
 [warning] The "field_block:node:event:field_date_time" was not found
 [warning] The "field_block:node:event:field_location" was not found
 [warning] The "field_block:node:event:field_meta_tags" was not found
 [warning] The "field_block:node:event:field_map_location" was not found
 [warning] The "field_block:node:event:field_image" was not found
 [warning] The "extra_field_block:node:event:links" was not found
 [warning] The "field_block:node:event:body" was not found
 [warning] The "extra_field_block:node:event:content_moderation_control" was not found
 [warning] The "field_block:node:event:field_date_time" was not found
 [warning] The "field_block:node:event:field_location" was not found
 [warning] The "field_block:node:event:field_meta_tags" was not found
 [warning] The "field_block:node:event:field_map_location" was not found
 [warning] The "block_content:aa33cb62-047a-4695-a523-aa43266c2bb3" was not found
 [warning] The User-Agent must be set to use the Nominatim provider.
 [warning] Unable to geocode 'Kennedy Space Center Visitor Complex Space Commerce Way MERRITT ISLAND, FL 32953 US'.
 [notice] Performed install task: starshot_installer_apply_recipes
 [notice] Performed install task: starshot_installer_configure_geocoder
 [notice] Performed install task: starshot_installer_uninstall_myself
 [notice] Performed install task: install_finished
 [success] Installation complete.
> drush webform-libraries-download
Removing existing libraries…
Downloading https://github.com/components/codemirror/archive/refs/tags/5.65.12.zip
Extracting to /var/www/html/web/libraries/codemirror
Downloading https://github.com/RobinHerbots/jquery.inputmask/archive/refs/tags/5.0.8.zip
Extracting to /var/www/html/web/libraries/jquery.inputmask
Downloading https://github.com/jackocnr/intl-tel-input/archive/refs/tags/v17.0.19.zip
Extracting to /var/www/html/web/libraries/jquery.intl-tel-input
Downloading https://github.com/gjunge/rateit.js/archive/refs/tags/1.1.5.zip
Extracting to /var/www/html/web/libraries/jquery.rateit
Downloading https://github.com/select2/select2/archive/refs/tags/4.0.13.zip
Extracting to /var/www/html/web/libraries/jquery.select2
Downloading https://github.com/ractoon/jQuery-Text-Counter/archive/refs/tags/0.9.1.zip
Extracting to /var/www/html/web/libraries/jquery.textcounter
Downloading https://github.com/jonthornton/jquery-timepicker/archive/refs/tags/1.14.0.zip
Extracting to /var/www/html/web/libraries/jquery.timepicker
Downloading https://registry.npmjs.org/@popperjs/core/-/core-2.11.6.tgz
Extracting to /var/www/html/web/libraries/popperjs
Downloading https://github.com/NigelOToole/progress-tracker/archive/refs/tags/2.0.7.zip
Extracting to /var/www/html/web/libraries/progress-tracker
Downloading https://github.com/szimek/signature_pad/archive/refs/tags/v2.3.0.zip
Extracting to /var/www/html/web/libraries/signature_pad
Downloading https://github.com/cferdinandi/tabby/archive/refs/tags/v12.0.3.zip
Extracting to /var/www/html/web/libraries/tabby
Downloading https://registry.npmjs.org/tippy.js/-/tippy.js-6.3.7.tgz
Extracting to /var/www/html/web/libraries/tippyjs
`
That being said the site pops up and things appear to work correctly including the map

Screenshot 2024-07-03 124134

**Comment by phenaproxima** [comment]
Yeah the warnings are normal. They weren't caused by this PR, and don't seem to affect anything. Don't worry about 'em. :)

**Comment by phenaproxima** [comment]
@gitressa I installed Leaflet More Maps but I can't figure out how to freaking configure it. Halp!

**Comment by gitressa** [comment]
Perfect @phenaproxima, I now get Leaflet map tiles served from openstreetmap.de, hosted in Germany. Thanks!

**Comment by phenaproxima** [comment]
Nice. I think the only thing I'd like to see before merging this is an issue opened against Geocoder to set default values for the Nominatim provider, to reduce the need to configure stuff. Can you open that, @gitressa?

**Comment by phenaproxima** [comment]
Yes, but against the Geocoder module on d.o, not here. :)

**Comment by gitressa** [comment]
Heh, gotcha :) 

I created  [Add Token support for Nominatim provider, and possibly others](https://www.drupal.org/project/geocoder/issues/3459311).

**Comment by phenaproxima** [comment]
Thanks! Merging this.

**Comment by gitressa** [comment]
Nice, it works beautifully, thanks! Perfect way to reach the weekend, with two Starshot GDPR successes, here and also:
- https://github.com/mglaman/wasm-drupal/issues/33

**Pull request merged**
