### PR TITLE
Add Same Page Preview

### PR DESCRIPTION
**Pull request by phenaproxima**
Addresses #17.

Now that I was able to patch it to get it to work (thanks @cosmicdreams et al!), I think this module is super cool. It's not perfect, but it's a real-life preview that actually works. This PR adds it to all content types.

I'd like to get a few folks to try this out and get some opinions before I merge it, but consider this a +1 from me.

### CODE REVIEW

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Comment by catch56** [comment]
Core has full site preview via workspaces, I think we should concentrate on showcasing that. I realise the use-case is different but 1. it is in core 2. hardly anyone knows about it. 3. it just became stable.

I haven't used the same page preview module but it seems like it should be a product decision whether the feature is desirable at all before adding yet another module.

**Comment by rpkoller** [comment]
In regards of the out of the box experience there is currently an issue that breaks the preview in Safari: https://www.drupal.org/project/same_page_preview/issues/3355708  . I've added the link per the request of @phenaproxima top the issue who considers it a blocker.

**Comment by phenaproxima** [comment]
I want to just quickly state _why_ I think this is a worthy addition to Starshot (and hopefully core), although I agree with @catch56's point about Workspaces.

To me, this addresses a _very_ different use case than Workspaces. I think Same Page Preview really gets down to the question an editor might reasonably have: "what is **this one page** going to _look like_?" It is a very tightly scoped preview. Layout Builder, despite its current clunkiness, also answers that question; presumably Experience Builder will too. Once XB is ready -- or heck, even if Starshot finds the right set of modules to spruce up the LB experience -- I think Same Page Preview's necessity may need to be reevaluated.

Workspaces, to me, is a bigger sort of preview. I'm not sure it really fits, in the UX sense, as something you use to preview single pieces of content. To me, it's there to answer the question of "what will my site as a whole be like, with all these changes published"?

**Comment by catch56** [comment]
Workspaces allows you to save a draft of an entity, and then immediately see exactly how it will look in the context of the entire site.

This includes not only the canonical route page view, but also how it looks in listings. And that preview includes any nested entities that might be created as a result of the form submission - file uploads, media, auto-create tags, menu links, path aliases, etc.

**Comment by phenaproxima** [comment]
There is, however, something to be said for having the changes appear _while you're doing them_.

But as I said, that advantage might be conferred by LB/XB too, if we can get it working in a useful way.

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Comment by cosmicdreams** [comment]
Hey team!  Thanks for considering bringing this module in.

As @phenaproxima and our demo video at the top of our module page points out the module's purpose is to give content creators the ability to tinker their way into creating the content they want.

When you have "live" preview on hand you don't have to worry so much about how complicated you have made the content creation process.  The complexity melts away when you can immediately see the results of your edits.

That said I'm very excited about the workspace preview, this is the second time I've heard about in consecutive days.  I totally want to be working with workspaces and think some of clients could benefit from that kind of batch publishing.

But does it help out the low skill / nervous or straight-up apprehensive about "this web thing" content creator?  I'll have to see.

I should also note that "live preview" is a competitive advantage that some other CMS tools have over Drupal.  It sounds like we may choose to not include a feature like this one and allow other platforms to keep that competitive advantage.  If so, we should have a clear reason why we would want to do that.

P.S: 
Someone called out a safari issue.  I'll double check that but I think that might be a really old issue that we couldn't reproduce.

**Comment by rpkoller** [comment]
@cosmicdreams for me the issue persists for months. and i've just rechecked and installed a new starshot instance and installed same page preview. 
Screenshot 2024-05-11 at 18 20 59

**Comment by cosmicdreams** [comment]
Ah cool.  Let jump into the issue and see if we can handle it.

**Comment by catch56** [comment]
@cosmicdreams note this project is a prototype, the actual starshot project is here https://www.drupal.org/project/starshot and doesn't have code yet.

I think the process should be something like this:

1. The ideas queue issue should be reviewed by a core product manager (I tagged it for this yesterday, it wasn't previously tagged). If they decide this is something to try to get into core, (to replace core noe/comment preview?), that's great and a good reason to try to add it to starshot.

2. If they don't think it should be in core, but do think it should be in starshot (similar to Gin for the time being), then we could go ahead.

However for me that product/UX evaluation, and an idea of whether it's headed for core etc. should be the first step, not the last here.

For me personally there is a bit of overlap with layout builder preview and workspaces preview, and I don't know the implications of that but I do think these things should be considered together.

**Comment by cosmicdreams** [comment]
Just being considered is what I've been hoping for.  

Since the start of our development of same_page_preview we have made architectural choices that were all aimed and reducing the barrier of getting this work into core.  If this module was in core much of the work it does would fall away and we would simply modify the existing Node Preview functionality.  We are prepared to demonstrate the change set if needed.

When it comes to layout builder and workspace contexts, don't close the book on us just yet.  We would love to learn more about those contexts and have time to show how we can be helpful.

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr61-pycqtqbqe2d8pujogli3088exrdfcluk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663e4960bf7868a56358b9f4

**Pull request closed without merging**
